import { lazy } from 'react'

export const Home = lazy(() => import('../pages/Home'))
export const Catalog = lazy(() => import('../pages/Catalog'))
export const BookDetails = lazy(() => import('../pages/BookDetails'))
export const BookForm = lazy(() => import('../pages/BookForm'))
export const CreatePost = lazy(() => import('../pages/CreatePost'))
export const EditPost = lazy(() => import('../pages/EditPost'))
export const DonationFlow = lazy(() => import('../pages/DonationFlow'))
export const DonationsHistory = lazy(() => import('../pages/DonationsHistory'))
export const Institutions = lazy(() => import('../pages/Institutions'))
export const Notifications = lazy(() => import('../pages/Notifications'))
export const Profile = lazy(() => import('../pages/Profile'))
export const ProfileEdit = lazy(() => import('../pages/ProfileEdit'))
export const ProfileNotifications = lazy(
  () => import('../pages/ProfileNotifications')
)
export const PublicProfile = lazy(() => import('../pages/PublicProfile'))
export const SocialFeed = lazy(() => import('../pages/SocialFeed'))
export const TradeChat = lazy(() => import('../pages/TradeChat'))
export const TradeDetails = lazy(() => import('../pages/TradeDetails'))
export const TradeProposal = lazy(() => import('../pages/TradeProposal'))
export const TradeReview = lazy(() => import('../pages/TradeReview'))
export const TradesHistory = lazy(() => import('../pages/TradesHistory'))
export const AdminDashboard = lazy(() => import('../pages/AdminDashboard'))
export const AdminGenres = lazy(() => import('../pages/AdminGenres'))
export const AdminInstitutions = lazy(
  () => import('../pages/AdminInstitutions')
)
export const AdminReports = lazy(() => import('../pages/AdminReports'))
export const AdminUsers = lazy(() => import('../pages/AdminUsers'))
export const Login = lazy(() => import('../pages/Login'))
export const GoogleAuthCallback = lazy(
  () => import('../pages/GoogleAuthCallback')
)
export const CompleteProfile = lazy(() => import('../pages/CompleteProfile'))
export const Register = lazy(() => import('../pages/Register'))
export const VerifyEmail = lazy(() => import('../pages/VerifyEmail'))
export const ForgotPassword = lazy(() => import('../pages/ForgotPassword'))
export const ResetPassword = lazy(() => import('../pages/ResetPassword'))
export const NotFound = lazy(() => import('../pages/NotFound'))
